export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const GET_PRODUCT_INFO = "GET_PRODUCT_INFO";

export const ADD_TO_CART = "ADD_TO_CART";

export const ADDED_TO_CART = "ADDED_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const REMOVED_FROM_CART = "REMOVED_FROM_CART";
